development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://rbzxaangajgunu:GlXC3lspipW2WUaYwElaq0ZRKB@ec2-174-129-223-35.compute-1.amazonaws.com:5432/d4s23nlqtdlkfo
