# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 985334a1b92b2727f2f97adaf3be2f5f72afc0c4d4c1c8ecadd8fb5074064f8f45ec940c117d90d8328fa55bc6be0fdd1ec055496470fb4fcac4bb0ea155fe7e

test:
  secret_key_base: 003bdda53447a9cd6c15e575c9729d538b10963f22e16f27d5fc24b87c461f8850a4e9c36561083e125b9aa6c157391a303210ed5003234b8703084cd4f582ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
